# ubuntu-lts-to-24.04.yml
- name: Bring all Ubuntu LTS hosts up to 24.04 (rolling)
  hosts: ubuntu
  become: true
  gather_facts: true
  serial: 1

  vars:
    apt_cache_valid_time: 3600
    noninteractive_env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: a        # auto-restart services when needed

  pre_tasks:
    - name: Make sure APT cache is fresh
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Upgrade current release packages (safe)
      ansible.builtin.apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes

    - name: Ensure release upgrader is present
      ansible.builtin.apt:
        name: update-manager-core
        state: present

    - name: Set Prompt=lts for release upgrades
      ansible.builtin.lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: '^Prompt='
        line: 'Prompt=lts'

    - name: Check if a pre-upgrade reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_flag

    - name: Reboot before release upgrade if required
      ansible.builtin.reboot:
        reboot_timeout: 1800
      when: reboot_flag.stat.exists

    - name: Wait and refresh facts after pre-reboot
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 900
      when: reboot_flag.stat.exists

    - name: Re-gather facts after pre-reboot
      ansible.builtin.setup:
      when: reboot_flag.stat.exists

  tasks:
    # Initial status
    - name: Set is_noble flag
      ansible.builtin.set_fact:
        is_noble: "{{ ansible_distribution_version is version('24.04', '==') }}"


    # Perform up to 2 hops; next iteration will skip once is_noble becomes true
    - name: Perform release-upgrade hops (max 2)
      ansible.builtin.include_tasks: upgrade_hop.yml
      loop: "{{ range(1, 4) | list }}"     # 1..3
      loop_control:
        label: "hop {{ item }}"
      when: not is_noble                   # re-evaluated each iteration
      vars:
        hop_no: "{{ item }}"